#############################################
# Start analysis only looking at PA CEMS data
#############################################

# Install packages
install.packages("lubridate")
install.packages("sp")
install.packages("raster")
install.packages("rasterVis")
install.packages("maptools")
install.packages("rgeos")
install.packages("rgdal")
install.packages("ggmap")
install.packages("readxl")
install.packages("dplyr")
install.packages("chron")
install.packages("FinCal")
install.packages("xlsx")
install.packages("grid")
install.packages("ggplot2")
install.packages("plyr")
install.packages("scales")
install.packages("rworldmap")
install.packages("data.table")
install.packages("httr")
install.packages("XML")
install.packages("reshape2")
install.packages("ggthemes")

library(lubridate)
library(sp)  # classes for spatial data
library(raster)  # grids, rasters
library(rasterVis)  # raster visualisation
library(maptools)
library(rgeos)
library(rgdal)
library(ggmap)
library(readxl)
library(dplyr)
library(chron)
library(FinCal)
library(xlsx)
library(grid)
library(ggplot2)
library(plyr)
library(scales)
library(ggthemes)
library(rworldmap)
library(data.table)
library(httr)
library(XML)
library(reshape2)

# Set working directory
setwd("C:/Users/nhanus/Documents/Marginal-Plant-Analysis")


# Read in data
pa01_2016 <- read.csv(file = "C:/Users/nhanus/Documents/Marginal-Plant-Analysis/2016pa01.csv", header = TRUE, sep = ",", stringsAsFactors=FALSE)
pa02_2016 <- read.csv(file = "C:/Users/nhanus/Documents/Marginal-Plant-Analysis/2016pa02.csv", header = TRUE, sep = ",", stringsAsFactors=FALSE)
pa03_2016 <- read.csv(file = "C:/Users/nhanus/Documents/Marginal-Plant-Analysis/2016pa03.csv", header = TRUE, sep = ",", stringsAsFactors=FALSE)
pa04_2016 <- read.csv(file = "C:/Users/nhanus/Documents/Marginal-Plant-Analysis/2016pa04.csv", header = TRUE, sep = ",", stringsAsFactors=FALSE)
pa05_2016 <- read.csv(file = "C:/Users/nhanus/Documents/Marginal-Plant-Analysis/2016pa05.csv", header = TRUE, sep = ",", stringsAsFactors=FALSE)
pa06_2016 <- read.csv(file = "C:/Users/nhanus/Documents/Marginal-Plant-Analysis/2016pa06.csv", header = TRUE, sep = ",", stringsAsFactors=FALSE)
pa07_2016 <- read.csv(file = "C:/Users/nhanus/Documents/Marginal-Plant-Analysis/2016pa07.csv", header = TRUE, sep = ",", stringsAsFactors=FALSE)
pa08_2016 <- read.csv(file = "C:/Users/nhanus/Documents/Marginal-Plant-Analysis/2016pa08.csv", header = TRUE, sep = ",", stringsAsFactors=FALSE)
pa09_2016 <- read.csv(file = "C:/Users/nhanus/Documents/Marginal-Plant-Analysis/2016pa09.csv", header = TRUE, sep = ",", stringsAsFactors=FALSE)
pa10_2016 <- read.csv(file = "C:/Users/nhanus/Documents/Marginal-Plant-Analysis/2016pa10.csv", header = TRUE, sep = ",", stringsAsFactors=FALSE)

# Interested in GLOAD (MW) = Gross Load = Rate of electrical generation of a unit or source produced by combusting a given heat input of fuel
# SLOAD (1000lb/hr) = Rate of steam pressure generated by a unit or source produced by combusting a given heat input of fuel.






