#############################################
# Start analysis only looking at PA CEMS data
#############################################

# Install packages
install.packages("lubridate")
install.packages("sp")
install.packages("raster")
install.packages("rasterVis")
install.packages("maptools")
install.packages("rgeos")
install.packages("rgdal")
install.packages("ggmap")
install.packages("readxl")
install.packages("dplyr")
install.packages("chron")
install.packages("FinCal")
install.packages("xlsx")
install.packages("grid")
install.packages("ggplot2")
install.packages("plyr")
install.packages("scales")
install.packages("rworldmap")
install.packages("data.table")
install.packages("httr")
install.packages("XML")
install.packages("reshape2")
install.packages("ggthemes")

library(lubridate)
library(sp)  # classes for spatial data
library(raster)  # grids, rasters
library(rasterVis)  # raster visualisation
library(maptools)
library(rgeos)
library(rgdal)
library(ggmap)
library(readxl)
library(dplyr)
library(chron)
library(FinCal)
library(xlsx)
library(grid)
library(ggplot2)
library(plyr)
library(scales)
library(ggthemes)
library(rworldmap)
library(data.table)
library(httr)
library(XML)
library(reshape2)

# Set working directory
setwd("C:/Users/nhanus/Documents/Marginal-Plant-Analysis")


# Read in data
pa01_2016 <- read.csv(file = "C:/Users/nhanus/Documents/Marginal-Plant-Analysis/2016pa01.csv", header = TRUE, sep = ",", stringsAsFactors=FALSE)
pa02_2016 <- read.csv(file = "C:/Users/nhanus/Documents/Marginal-Plant-Analysis/2016pa02.csv", header = TRUE, sep = ",", stringsAsFactors=FALSE)
pa03_2016 <- read.csv(file = "C:/Users/nhanus/Documents/Marginal-Plant-Analysis/2016pa03.csv", header = TRUE, sep = ",", stringsAsFactors=FALSE)
pa04_2016 <- read.csv(file = "C:/Users/nhanus/Documents/Marginal-Plant-Analysis/2016pa04.csv", header = TRUE, sep = ",", stringsAsFactors=FALSE)
pa05_2016 <- read.csv(file = "C:/Users/nhanus/Documents/Marginal-Plant-Analysis/2016pa05.csv", header = TRUE, sep = ",", stringsAsFactors=FALSE)
pa06_2016 <- read.csv(file = "C:/Users/nhanus/Documents/Marginal-Plant-Analysis/2016pa06.csv", header = TRUE, sep = ",", stringsAsFactors=FALSE)
pa07_2016 <- read.csv(file = "C:/Users/nhanus/Documents/Marginal-Plant-Analysis/2016pa07.csv", header = TRUE, sep = ",", stringsAsFactors=FALSE)
pa08_2016 <- read.csv(file = "C:/Users/nhanus/Documents/Marginal-Plant-Analysis/2016pa08.csv", header = TRUE, sep = ",", stringsAsFactors=FALSE)
pa09_2016 <- read.csv(file = "C:/Users/nhanus/Documents/Marginal-Plant-Analysis/2016pa09.csv", header = TRUE, sep = ",", stringsAsFactors=FALSE)
pa10_2016 <- read.csv(file = "C:/Users/nhanus/Documents/Marginal-Plant-Analysis/2016pa10.csv", header = TRUE, sep = ",", stringsAsFactors=FALSE)
pa11_2016 <- read.csv(file = "C:/Users/nhanus/Documents/Marginal-Plant-Analysis/2016pa11.csv", header = TRUE, sep = ",", stringsAsFactors=FALSE)
pa12_2016 <- read.csv(file = "C:/Users/nhanus/Documents/Marginal-Plant-Analysis/2016pa12.csv", header = TRUE, sep = ",", stringsAsFactors=FALSE)


# Combine PA datasets 1-10
pa_2016 <- rbind(pa01_2016, pa02_2016, pa03_2016, pa04_2016, pa05_2016, pa06_2016, pa07_2016, pa08_2016, pa09_2016, pa10_2016, pa11_2016, pa12_2016)

###########################
# Some key data definitions
###########################

# GLOAD (MW) = Gross load. Rate of electrical generation of a unit or source produced by combusting a given heat input of fuel.
# SLOAD (1000lb/hr) = Steam load. Rate of steam pressure generated by a unit or source produced by combusting a given heat input of fuel.
# OP_DATE = Day on which activity occurred.
# OP_HOUR = Hour in which acitvity occurred.
# OP_TIME = Any part of an hour in which a unit combusts any fuel.
# FACILITY_NAME = The name given by the owners and operators to a facility.
# ORISPL_CODE = The unique six-digit facility identification number, also called an ORISPL, assigned by the Energy Information Administration.
# UNITID = Unique identifier for each unit at a facility.
# FAC_ID = Unsure
# UNIT_ID = Unsure


# Check the class of every variable
class(pa_2016$STATE) # character
class(pa_2016$FACILITY_NAME) # character
class(pa_2016$ORISPL_CODE) # integer
class(pa_2016$UNITID) # character
class(pa_2016$OP_DATE) # character
class(pa_2016$OP_HOUR) # integer
class(pa_2016$OP_TIME) # numeric
class(pa_2016$GLOAD..MW.) # integer
class(pa_2016$SLOAD..1000lb.hr.) # integer
class(pa_2016$SO2_MASS..lbs.) # numeric
class(pa_2016$SO2_MASS_MEASURE_FLG) # character
class(pa_2016$SO2_RATE..lbs.mmBtu.) # numeric
class(pa_2016$SO2_RATE_MEASURE_FLG) # character
class(pa_2016$NOX_MASS..lbs.) # numeric
class(pa_2016$NOX_MASS_MEASURE_FLG) # character
class(pa_2016$NOX_RATE..lbs.mmBtu.) # numeric
class(pa_2016$NOX_RATE_MEASURE_FLG) # character
class(pa_2016$CO2_MASS..tons.) # numeric
class(pa_2016$CO2_MASS_MEASURE_FLG) # character
class(pa_2016$CO2_RATE..tons.mmBtu.) # numeric
class(pa_2016$CO2_RATE_MEASURE_FLG) # character
class(pa_2016$HEAT_INPUT..mmBtu.) # numeric
class(pa_2016$FAC_ID) # integer
class(pa_2016$UNIT_ID) # integer

# Change date - break into month, day and year
pa_2016$month <- as.numeric(substr(pa_2016$OP_DATE, 1, 2))
pa_2016$day   <- as.numeric(substr(pa_2016$OP_DATE, 4, 5))
pa_2016$year  <- as.numeric(substr(pa_2016$OP_DATE, 7, 10))

# Change some integers to numeric
pa_2016$OP_HOUR             <- as.numeric(pa_2016$OP_HOUR)
pa_2016$GLOAD..MW.          <- as.numeric(pa_2016$GLOAD..MW.)
pa_2016$SLOAD..1000lb.hr.   <- as.numeric(pa_2016$SLOAD..1000lb.hr.)

# Check the class of transformed variables
class(pa_2016$month) # numeric
class(pa_2016$day) # numeric
class(pa_2016$year) # numeric
class(pa_2016$OP_HOUR) # numeric
class(pa_2016$GLOAD..MW.) # numeric
class(pa_2016$SLOAD..1000lb.hr.) # numeric

# Count total observations for PA - across all plants and timestamps
nrow(pa_2016) # 1,477,992

# Unique facility names
nrow(pa_2016[!duplicated(pa_2016$FACILITY_NAME),]) # 74

# Unique ORISPL_codes
nrow(pa_2016[!duplicated(pa_2016$ORISPL_CODE),]) # 74

# Unique UNITIDs
nrow(pa_2016[!duplicated(pa_2016$UNITID),]) # 97

# Unique facility IDs
nrow(pa_2016[!duplicated(pa_2016$FAC_ID),]) # 74 - just giong to use ORISPL_Codes since we don't know what fac_id is

# Unique UNIT_IDs
nrow(pa_2016[!duplicated(pa_2016$UNIT_ID),]) # 177 - just going to use UNITIDs since we don't know what UNIT_ID is

# Consider one facility: ORISPL_CODE = 3096
nrow(pa_2016[which(pa_2016$ORISPL_CODE == 3096),]) # 26352 observations or 1.7% of all observations

# Count total non-NA GLOAD observations - across all plants and timestamps
nrow(pa_2016[!is.na(pa_2016$GLOAD..MW.),]) # 443,409 or 30%

# Count total non-NA CO2 emissions obervations - across all plants and timestamps
nrow(pa_2016[!is.na(pa_2016$CO2_MASS..tons.),]) # 493643 or 33%

# Count times that GLOAD is NA and CO2 emissions is non-NA
nrow(pa_2016[which(is.na(pa_2016$GLOAD..MW.) & !is.na(pa_2016$CO2_MASS..tons.)),]) # 77,872 or 5% of data

# Count times that GLOAD is non-NA and CO2 emissions is NA
nrow(pa_2016[which(!is.na(pa_2016$GLOAD..MW.) & is.na(pa_2016$CO2_MASS..tons.)),]) # 27,638 or 2% of data

# Look at total distribution of GLOAD
hist(pa_2016$GLOAD..MW.) # fairly normal

# Look at total distribution of CO2 emisisons
hist(pa_2016$CO2_MASS..tons.) # right skew

